---
title: "everybody.codes.q7"
author: "Ben Jefferies"
date: "2025-11-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE}
library(here)
library(tidyverse)
```

# Everybody Codes 2025

Information about each challenge can be found at everybody.codes

## Quest 7

### Part 1

```{r}
notes_7.1 <- readLines(con = here("everybody_codes_e2025_q07_p1.txt"))

names_7.1 <- as.vector( strsplit( notes_7.1[1], ",")[[1]] )

rules_7.1 <- notes_7.1[3:length(notes_7.1)]

rules_7.1
```




```{r}
# create rules list, first only assigning the text after > to each element of list
rules_list <- lapply(rules_7.1, function(x) {
  parts <- trimws(strsplit(x, ">", fixed = TRUE)[[1]])   # split by >
  strsplit(parts[2], ",")[[1]]                           # split right side by commas
})


# assign names of rules list, using characters before >
names(rules_list) <- sapply(rules_7.1, function(x) trimws(strsplit(x, ">", fixed = TRUE)[[1]][1]))

# rules_list
# 
# which(names(rules_list) == "z")
# 
# names(rules_list) <- sapply(rules_list, "[", 1)
```



```{r}

name_check <- function(names) {

  index <- 1
  
  valid_indices <- c()
  
  for(name in names){
    
    letters <- as.vector( strsplit(name, "")[[1]] )  #split name into vector of chars
    
    n <- length(letters)-1 #don't check last letter
    
    check_sum <- 0
    
    # loop over each letter in the name to check if next one follows rules
    for(l in 1:n) {
      
      rule_index <- which(names(rules_list) == letters[l]) #find element of rules_list
      
      if(letters[l+1] %in% rules_list[[rule_index]]) {
        check_sum <- check_sum + 1
      }
      
    }
    
    if(check_sum == n) { 
      valid_indices <- c(valid_indices, index) 
      index <- index + 1
      } else { index <- index + 1 }
    
  }

  return(names[valid_indices])
  
}


name_check(names = names_7.1)


```

```{r}
letters <- as.vector( strsplit(names_7.1, "")[[1]] )

letters

for(l in 1:(length(letters)-1)){
  print(l)
}

```







### Part 2

Now multiple names can match, need to return the names and the sum of all of the indices of the matching names.


```{r}
notes_7.2 <- readLines(con = here("everybody_codes_e2025_q07_p2.txt"))

# extract and split all elements of the first line of the notes
names_7.2 <- as.vector( strsplit( notes_7.2[1], ",")[[1]] )

# rules are located in lines 3 and beyond
rules_7.2 <- notes_7.2[3:length(notes_7.2)]
```


```{r}
# create rules list, first only assigning the text after > to each element of list
rules_list <- lapply(rules_7.2, function(x) {
  parts <- trimws(strsplit(x, ">", fixed = TRUE)[[1]])   # split by >
  strsplit(parts[2], ",")[[1]]                           # split right side by commas
})


# assign names of rules list, using characters before >
names(rules_list) <- sapply(rules_7.2, function(x) trimws(strsplit(x, ">", fixed = TRUE)[[1]][1]))

```



```{r}

names_checker <- function(names) {

  index <- 1
  
  valid_indices <- c()
  
  for(name in names){
    
    letters <- as.vector( strsplit(name, "")[[1]] )  #split name into vector of chars
    
    n <- length(letters)-1 #don't check last letter
    
    check_sum <- 0
    
    # loop over each letter in the name to check if next one follows rules
    for(l in 1:n) {
      
      rule_index <- which(names(rules_list) == letters[l]) #find element of rules_list
      
      if(letters[l+1] %in% rules_list[[rule_index]]) {
        check_sum <- check_sum + 1
      }
      
    }
    
    if(check_sum == n) { 
      valid_indices <- c(valid_indices, index) 
      index <- index + 1
      } else { index <- index + 1 }
    
  }

  result_list <- list(names = names[valid_indices],
                      sum_index = sum(valid_indices, na.rm = T))
  
  return(result_list)
  
}

names_checker(names_7.2)
```

